### suppression d'une catégorie
DELETE http://localhost:3001/categorys/13

### Récupération des catégories
GET http://localhost:3001/categorys

### Récupération d'une catégorie par ID
GET http://localhost:3001/categorys/2

### Enregister une catégorie dans la BDD
POST http://localhost:3001/categorys
Content-Type: application/x-www-form-urlencoded

name=abc
&color=test
&image=123

### Modifier une catégorie dans la BDD
PATCH  http://localhost:3001/categorys/2
Content-Type: application/x-www-form-urlencoded

name=abc
&color=blue
&image=yellow

### Récupérer tout les services d'une catégorie par ID
GET http://localhost:3001/categorys/7/services

### Récupération des services
GET http://localhost:3001/v1/allServices

### Récupération d'un service
GET http://localhost:3001/v1/service/2

### Suppression d'un service
DELETE http://localhost:3001/v1/service/2

### Modification d'un service
PATCH  http://localhost:3001/v1/service/2
Content-Type: application/x-www-form-urlencoded

title=Peche artisanal
&duration=2 heures
&description=Peche à la truite
&online=oui
&irl=oui
&is_published=oui

### register
POST http://localhost:3001/v1/register
Content-Type: application/x-www-form-urlencoded

firstname=test
&lastname=test
&email=test@test.com
&password=Test001$
